name: Complex

on: push

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - run: date
    windows: windows-latest
        runs-on:
        - run: date
    macos:
        runs-on: macos-latest
        - run: date
     depends:  
      needs: ubuntu,windows,macos
      runs-on: macos-latest
      - run: date
        
            
